import './style.css';
import {buildToolbox,equipmentDefaults,registerArduinoBlocks} from './blocks.js';
import {createArduinoGenerator} from './generator.js';

const Blockly=window.ScratchBlocks;
if(!Blockly)throw new Error('TurboWarp Scratch Blocks failed to load.');
let equipment;try{equipment=JSON.parse(localStorage.getItem('turboarduino-equipment'))||equipmentDefaults()}catch{equipment=equipmentDefaults()}
registerArduinoBlocks(Blockly,equipment);
const toolbox=buildToolbox(equipment);
const app=document.querySelector('#app');
app.innerHTML=`<header class="menu-bar"><div class="tw-logo" title="TurboWarp Arduino"><span class="logo-mark">∞</span><span class="logo-type"><b>TurboWarp</b><em>Arduino Studio</em></span></div><nav class="main-menu" aria-label="Main menu"><div class="menu"><button class="menu-trigger" aria-haspopup="true" aria-expanded="false">File</button><div class="menu-popover"><button id="new-project">New project</button><button id="load-project">Load from your computer</button><button id="save-project">Save to your computer</button><div class="menu-separator"></div><button id="save-ino">Download Arduino code</button></div></div><div class="menu"><button class="menu-trigger" aria-haspopup="true" aria-expanded="false">Edit</button><div class="menu-popover"><button id="undo">Undo</button><button id="redo">Redo</button><div class="menu-separator"></div><button id="clear-blocks">Delete all blocks</button></div></div><div class="menu"><button class="menu-trigger" aria-haspopup="true" aria-expanded="false">Settings</button><div class="menu-popover"><span class="menu-label">Appearance</span><button class="theme-choice" data-theme="light">Light</button><button class="theme-choice" data-theme="dark">Dark</button><button class="theme-choice" data-theme="system">System default</button></div></div><button id="help" class="plain-menu">Help</button></nav><div class="project-title"><input id="project-name" value="Untitled" aria-label="Project title"></div><div class="top-actions"><button id="theme-toggle" class="icon-button" aria-label="Switch to dark mode" title="Switch appearance"><span aria-hidden="true">☾</span></button><select id="transport" class="transport" aria-label="Connection method"><option value="usb">USB cable</option><option value="bluetooth">Bluetooth</option></select><button id="connect" class="white-button"><span class="connection-dot"></span> Connect</button><button id="upload" class="upload">Upload <span aria-hidden="true">↗</span></button></div></header>
<main class="body-wrapper"><section class="editor-wrapper"><div class="workspace-bar"><div class="editor-tabs"><button class="tab active" data-panel="blocks"><span>◫</span> Code</button><button class="tab" data-panel="arduino"><span>⌨</span> Arduino C++</button><button class="tab" data-panel="console"><span>▤</span> Serial</button></div><div class="workspace-hint"><span></span> Drag blocks to build your sketch</div></div><div class="editor-content"><section id="blocks-panel" class="panel active"><div id="blockly"></div><button id="add-extension" class="extension" title="Add Extension">＋</button></section><section id="arduino-panel" class="panel code-panel"><div class="code-head"><b>sketch.ino</b><button id="download">Download .ino</button></div><pre id="arduino-code"></pre></section><section id="console-panel" class="panel console-panel"><div id="console"><p>Connect an Arduino with a USB data cable to open the serial monitor.</p></div><div class="send"><input id="serial-input" placeholder="Send a line…" disabled><button id="serial-send" disabled>Send</button></div></section></div></section><aside class="stage-pane"><div class="stage-menu"><div class="run-controls"><button class="run" title="Generate and run">▶</button><button class="stop" title="Disconnect">■</button></div><div class="stage-size"><button title="Small stage">◩</button><button class="selected" title="Large stage">▣</button><button title="Full screen">⛶</button></div></div><div class="device-stage"><div class="stage-status"><span id="status">Arduino offline</span><i></i></div><div class="arduino-board"><div class="usb-port"></div><div class="pin-row top"></div><div class="board-chip"></div><strong>ARDUINO</strong><b>UNO</b><div class="pin-row bottom"></div><div class="board-led"></div></div><p>Connect with a USB data cable</p></div><div class="device-selector"><div class="device-info"><span class="device-thumb">∞</span><label>Board<select id="board" aria-label="Board"><option value="uno">Arduino Uno</option><option value="nano">Arduino Nano</option><option value="nanoOldBootloader">Nano (old bootloader/clone)</option><option value="proMini">Pro Mini</option><option value="lgt8f328p">LGT8F328P / modified Uno</option><option value="mega">Mega 2560</option><option value="custom">Custom / modified board…</option></select></label></div><button class="add-device" title="Choose an Arduino board">＋</button></div></aside></main>
<div id="modal" class="modal" hidden><div class="dialog"><button class="close" aria-label="Close">×</button><h2>Upload firmware</h2><p>Choose USB for standard AVR bootloaders, or Bluetooth for a board/custom receiver that accepts firmware data over a BLE characteristic.</p><label>Connection<select id="upload-transport"><option value="usb">USB cable</option><option value="bluetooth">Bluetooth (custom OTA)</option></select></label><div id="bluetooth-settings" hidden><label>BLE service UUID<input id="ble-service" value="0000ffe0-0000-1000-8000-00805f9b34fb"></label><label>BLE write characteristic UUID<input id="ble-characteristic" value="0000ffe1-0000-1000-8000-00805f9b34fb"></label></div><label>1. Firmware file<input id="hex-file" type="file" accept=".hex,text/plain"></label><label>2. Upload profile<select id="upload-board"><option value="uno">Uno / Optiboot</option><option value="nano">Nano (new bootloader)</option><option value="nanoOldBootloader">Nano / clone (old bootloader)</option><option value="proMini">Pro Mini</option><option value="lgt8f328p">LGT8F328P</option></select></label><label class="verify"><input id="verify" type="checkbox" checked> Verify after uploading</label><button id="flash" class="flash">Choose a .hex file</button><progress id="progress" max="100" value="0"></progress><small id="upload-note">Web Serial requires desktop Chrome or Edge and HTTPS.</small></div></div>
<div id="toast" class="toast" role="status"></div>`;

const projectPicker=Object.assign(document.createElement('input'),{type:'file',accept:'.twa,.json,.xml'});projectPicker.hidden=true;projectPicker.id='project-picker';document.body.append(projectPicker);

Blockly.ScratchMsgs?.setLocale?.('en');
const workspace=Blockly.inject('blockly',{toolbox,media:'../media/',scrollbars:true,trashcan:false,comments:true,zoom:{controls:true,wheel:true,startScale:.8,maxScale:1.4,minScale:.35,scaleSpeed:1.1}});
const generator=createArduinoGenerator();
const $=selector=>document.querySelector(selector);let port,reader,bleDevice,bleCharacteristic;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function generate(){const code=generator.workspaceToCode(workspace);$('#arduino-code').textContent=code;return code}
const saved=localStorage.getItem('turboarduino-workspace');if(saved){try{Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(saved),workspace)}catch{localStorage.removeItem('turboarduino-workspace')}}
workspace.addChangeListener(()=>{clearTimeout(window.saveTimer);window.saveTimer=setTimeout(()=>localStorage.setItem('turboarduino-workspace',Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace))),250)});
$('.editor-tabs').addEventListener('click',event=>{const button=event.target.closest('.tab');if(!button)return;if(button.dataset.panel==='arduino')generate();document.querySelectorAll('.tab,.panel').forEach(el=>el.classList.remove('active'));button.classList.add('active');$(`#${button.dataset.panel}-panel`).classList.add('active');if(button.dataset.panel==='blocks')setTimeout(()=>Blockly.svgResize(workspace))});
$('.run').onclick=()=>{generate();toast('Arduino code generated')};$('.stop').onclick=async()=>{await reader?.cancel();await port?.close();port=null;$('#status').textContent='Arduino offline'};
$('#project-name').value=localStorage.getItem('turboarduino-name')||'Untitled';$('#project-name').oninput=e=>localStorage.setItem('turboarduino-name',e.target.value);
function downloadFile(contents,name,type){const url=URL.createObjectURL(new Blob([contents],{type}));const link=Object.assign(document.createElement('a'),{href:url,download:name});link.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function safeName(){return $('#project-name').value.replace(/[^a-z0-9_-]/gi,'_')||'Untitled'}
function closeMenus(){document.querySelectorAll('.menu.open').forEach(menu=>{menu.classList.remove('open');menu.querySelector('.menu-trigger').setAttribute('aria-expanded','false')})}
document.querySelector('.main-menu').addEventListener('click',event=>{const trigger=event.target.closest('.menu-trigger');if(!trigger)return;const menu=trigger.parentElement;const opening=!menu.classList.contains('open');closeMenus();menu.classList.toggle('open',opening);trigger.setAttribute('aria-expanded',String(opening))});
document.addEventListener('click',event=>{if(!event.target.closest('.main-menu'))closeMenus()});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenus()});
$('#new-project').onclick=()=>{if(workspace.getAllBlocks(false).length&& !confirm('Create a new project and delete all blocks?'))return;workspace.clear();$('#project-name').value='Untitled';localStorage.removeItem('turboarduino-workspace');localStorage.setItem('turboarduino-name','Untitled');closeMenus();toast('New empty project created')};
$('#load-project').onclick=()=>{closeMenus();projectPicker.click()};
projectPicker.onchange=async()=>{const file=projectPicker.files[0];if(!file)return;try{const text=await file.text();let xml=text;let name=file.name.replace(/\.(twa|json|xml)$/i,'');if(!file.name.toLowerCase().endsWith('.xml')){const data=JSON.parse(text);if(data.format!=='TurboWarp Arduino Project'||typeof data.workspace!=='string')throw new Error('Not a TurboWarp Arduino project');xml=data.workspace;name=data.name||name}const dom=Blockly.Xml.textToDom(xml);workspace.clear();Blockly.Xml.domToWorkspace(dom,workspace);$('#project-name').value=name;localStorage.setItem('turboarduino-name',name);toast(`Loaded ${file.name}`)}catch(error){toast(`Could not load project: ${error.message}`)}finally{projectPicker.value=''}};
$('#save-project').onclick=()=>{const project={format:'TurboWarp Arduino Project',version:1,name:$('#project-name').value||'Untitled',workspace:Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace))};downloadFile(JSON.stringify(project,null,2),safeName()+'.twa','application/json');closeMenus();toast('Project saved')};
$('#undo').onclick=()=>{workspace.undo(false);closeMenus()};$('#redo').onclick=()=>{workspace.undo(true);closeMenus()};$('#clear-blocks').onclick=()=>{if(workspace.getAllBlocks(false).length&&confirm('Delete all blocks?'))workspace.clear();closeMenus()};
$('#help').onclick=()=>toast('Drag Arduino blocks into the workspace, save a .twa project, or generate and upload C++.');$('#add-extension').onclick=()=>{const name=prompt('Custom equipment name:','My sensor');if(!name)return;const kind=confirm('Does it OUTPUT a value? Press Cancel for an input/sensor.')?'output':'input';const port=prompt('Default port or pin (numbers, A0, SDA, or board aliases are allowed):',kind==='input'?'A0':'9')||'A0';equipment.push({id:`custom_${Date.now()}`,name,kind,port,template:kind==='input'?'analog':'pwm'});localStorage.setItem('turboarduino-equipment',JSON.stringify(equipment));registerArduinoBlocks(Blockly,equipment);workspace.updateToolbox(buildToolbox(equipment));toast(`${name} added to the Arduino extension`)};
function downloadSketch(){downloadFile(generate(),safeName()+'.ino','text/x-arduino')}
$('#download').onclick=downloadSketch;$('#save-ino').onclick=()=>{downloadSketch();closeMenus()};
function applyTheme(theme){const resolved=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;document.documentElement.dataset.theme=resolved;document.documentElement.dataset.themePreference=theme;document.querySelector('meta[name="theme-color"]').content=resolved==='dark'?'#0b1220':'#2563eb';document.querySelectorAll('.theme-choice').forEach(button=>button.classList.toggle('selected',button.dataset.theme===theme));const toggle=$('#theme-toggle');toggle.querySelector('span').textContent=resolved==='dark'?'☀':'☾';toggle.setAttribute('aria-label',resolved==='dark'?'Switch to light mode':'Switch to dark mode');Blockly.svgResize(workspace)}
const themePreference=localStorage.getItem('turboarduino-theme')||'system';applyTheme(themePreference);$('#theme-toggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('turboarduino-theme',next);applyTheme(next)};document.querySelectorAll('.theme-choice').forEach(button=>button.onclick=()=>{localStorage.setItem('turboarduino-theme',button.dataset.theme);applyTheme(button.dataset.theme);closeMenus()});matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((localStorage.getItem('turboarduino-theme')||'system')==='system')applyTheme('system')});
async function connect(){if($('#transport').value==='bluetooth'){if(!navigator.bluetooth)return toast('Bluetooth needs a Web Bluetooth browser.');try{const service=localStorage.getItem('turboarduino-ble-service')||'0000ffe0-0000-1000-8000-00805f9b34fb';const characteristic=localStorage.getItem('turboarduino-ble-characteristic')||'0000ffe1-0000-1000-8000-00805f9b34fb';bleDevice=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[service]});const server=await bleDevice.gatt.connect();bleCharacteristic=await (await server.getPrimaryService(service)).getCharacteristic(characteristic);$('#status').textContent=`${bleDevice.name||'Arduino'} connected · Bluetooth`;$('#serial-input').disabled=$('#serial-send').disabled=false;$('#console').innerHTML='<p class="good">● Bluetooth connected</p>'}catch(error){if(error.name!=='NotFoundError')toast(`Bluetooth failed: ${error.message}`)}return}if(!navigator.serial)return toast('Web Serial needs desktop Chrome or Edge.');try{port=await navigator.serial.requestPort();await port.open({baudRate:9600});$('#status').textContent='Arduino connected · 9600 baud';$('#serial-input').disabled=$('#serial-send').disabled=false;$('#console').innerHTML='<p class="good">● USB serial connected</p>';const decoder=new TextDecoderStream();port.readable.pipeTo(decoder.writable);reader=decoder.readable.getReader();while(port?.readable){const {value,done}=await reader.read();if(done)break;if(value){const line=document.createElement('pre');line.textContent=value;$('#console').append(line);$('#console').scrollTop=$('#console').scrollHeight}}}catch(error){if(error.name!=='NotFoundError')toast(`Connection failed: ${error.message}`)}}
$('#connect').onclick=connect;$('#serial-send').onclick=async()=>{const data=new TextEncoder().encode($('#serial-input').value+'\n');if(bleCharacteristic)await bleCharacteristic.writeValueWithoutResponse(data);else if(port?.writable){const writer=port.writable.getWriter();await writer.write(data);writer.releaseLock()}else return;$('#serial-input').value=''};
const modal=$('#modal');$('#upload').onclick=()=>{generate();$('#upload-board').value=['uno','nano','nanoOldBootloader','proMini','lgt8f328p'].includes($('#board').value)?$('#board').value:'uno';modal.hidden=false};$('.close').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};$('#hex-file').onchange=()=>{$('#flash').textContent=$('#hex-file').files[0]?'Flash firmware':'Choose a .hex file'};
$('#upload-transport').onchange=()=>{$('#bluetooth-settings').hidden=$('#upload-transport').value!=='bluetooth';$('#upload-note').textContent=$('#upload-transport').value==='bluetooth'?'Requires compatible BLE OTA firmware on the board.':'Web Serial requires desktop Chrome or Edge and HTTPS.'};
$('#flash').onclick=async()=>{const file=$('#hex-file').files[0];if(!file)return toast('Choose a compiled .hex firmware file first.');try{$('#flash').disabled=true;if($('#upload-transport').value==='bluetooth'){if(!navigator.bluetooth)throw new Error('Web Bluetooth is unavailable');const service=$('#ble-service').value.trim(),characteristic=$('#ble-characteristic').value.trim();localStorage.setItem('turboarduino-ble-service',service);localStorage.setItem('turboarduino-ble-characteristic',characteristic);const device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[service]});const server=await device.gatt.connect();const writer=await (await server.getPrimaryService(service)).getCharacteristic(characteristic);const bytes=new Uint8Array(await file.arrayBuffer());for(let offset=0;offset<bytes.length;offset+=128){await writer.writeValueWithoutResponse(bytes.slice(offset,offset+128));const value=Math.round(Math.min(offset+128,bytes.length)/bytes.length*100);$('#progress').value=value;$('#upload-note').textContent=`Sending over Bluetooth… ${value}%`}device.gatt.disconnect()}else{if(!navigator.serial)throw new Error('Web Serial is unavailable');$('#upload-note').textContent='Opening USB uploader…';const {upload,boards}=await import('web-arduino-uploader/dist/index.js');const url=URL.createObjectURL(file);await upload(boards[$('#upload-board').value],url,value=>{$('#progress').value=value;$('#upload-note').textContent=`Uploading… ${value}%`},$('#verify').checked);URL.revokeObjectURL(url)}$('#upload-note').textContent='Upload complete — your Arduino is running!';toast('Firmware uploaded successfully')}catch(error){$('#upload-note').textContent=`Upload failed: ${error.message}`;toast('Upload failed — check the board, profile, and connection.')}finally{$('#flash').disabled=false}};
$('#board').onchange=()=>{const custom=$('#board').value==='custom';if(custom){const name=prompt('Name this modified Arduino / compatible board:','Custom ATmega328P');if(name){$('#board').selectedOptions[0].textContent=name;localStorage.setItem('turboarduino-custom-board',name)}toast('Use Hardware blocks freely; pin numbers are not limited. Choose its bootloader profile when uploading.')}};
const customName=localStorage.getItem('turboarduino-custom-board');if(customName)$('#board').querySelector('[value=custom]').textContent=customName;
