const header='// Generated by TurboBot Studio\n#include <Arduino.h>\n\n';
const indent=source=>source.split('\n').filter(Boolean).map(line=>'  '+line).join('\n');
export function pythonToArduino(source){
 const setup=[],loop=[];let target=setup;
 const lines=source.split(/\r?\n/);
 for(let index=0;index<lines.length;index+=1){
  const line=lines[index].trim();if(!line||line.startsWith('#')||line==='from arduino import *')continue;
  if(line==='def setup():'){target=setup;continue} if(line==='def loop():'){target=loop;continue} if(line==='pass')continue;
  let match;
  if((match=line.match(/^pin_mode\((\d+),\s*(OUTPUT|INPUT|INPUT_PULLUP)\)$/i)))target.push('pinMode('+match[1]+', '+match[2].toUpperCase()+');');
  else if((match=line.match(/^digital_write\((\d+),\s*(HIGH|LOW|True|False|1|0)\)$/i))){const value=/^(high|true|1)$/i.test(match[2])?'HIGH':'LOW';target.push('digitalWrite('+match[1]+', '+value+');')}
  else if((match=line.match(/^analog_write\((\d+),\s*(\d+)\)$/i)))target.push('analogWrite('+match[1]+', '+match[2]+');');
  else if((match=line.match(/^sleep\((\d+(?:\.\d+)?)\)$/i)))target.push('delay('+Math.round(Number(match[1])*1000)+');');
  else if((match=line.match(/^print\((.+)\)$/)))target.push('Serial.println('+match[1]+');');
  else throw new Error('Line '+(index+1)+': I don’t understand “'+line+'”.');
 }
 return header+'void setup() {\n'+indent(['Serial.begin(9600);',...setup].join('\n'))+'\n}\n\nvoid loop() {\n'+indent(loop.join('\n'))+'\n}\n';
}
export function createArduinoGenerator(Blockly){
 const generator=new Blockly.Generator('Arduino');
 generator.scrub_=(block,code,thisOnly)=>{const next=block.nextConnection?.targetBlock();return code+(!thisOnly&&next?generator.blockToCode(next):'')};
 generator.forBlock.robot_start=block=>'void setup() {\n  Serial.begin(9600);\n}\n\nvoid loop() {\n'+generator.statementToCode(block,'DO')+'}\n';
 generator.forBlock.pin_mode=block=>'pinMode('+block.getFieldValue('PIN')+', '+block.getFieldValue('MODE')+');\n';
 generator.forBlock.digital_write=block=>'digitalWrite('+block.getFieldValue('PIN')+', '+block.getFieldValue('STATE')+');\n';
 generator.forBlock.analog_write=block=>'analogWrite('+block.getFieldValue('PIN')+', '+block.getFieldValue('VALUE')+');\n';
 generator.forBlock.wait_ms=block=>'delay('+block.getFieldValue('MS')+');\n';
 generator.forBlock.serial_print=block=>'Serial.println('+JSON.stringify(block.getFieldValue('TEXT'))+');\n';
 return generator;
}
