import './style.css';
import {registerArduinoBlocks,toolbox} from './blocks.js';
import {createArduinoGenerator} from './generator.js';

const Blockly=window.ScratchBlocks;
if(!Blockly)throw new Error('TurboWarp Scratch Blocks failed to load.');
registerArduinoBlocks(Blockly);
const app=document.querySelector('#app');
app.innerHTML=`<header class="menu-bar"><div class="tw-logo" title="TurboWarp Arduino"><span>⚡</span><b>TurboWarp</b></div><nav><button id="file">File</button><button id="examples">Edit</button><button id="help">Help</button></nav><div class="project-title"><input id="project-name" value="Blink" aria-label="Project title"></div><div class="top-actions"><button id="connect" class="white-button">Connect</button><button id="upload" class="upload">Upload</button></div></header>
<main class="body-wrapper"><section class="editor-wrapper"><div class="editor-tabs"><button class="tab active" data-panel="blocks"><span>◫</span> Code</button><button class="tab" data-panel="arduino"><span>⌨</span> Arduino C++</button><button class="tab" data-panel="console"><span>▤</span> Serial</button></div><div class="editor-content"><section id="blocks-panel" class="panel active"><div id="blockly"></div><button id="add-extension" class="extension" title="Add Extension">＋</button></section><section id="arduino-panel" class="panel code-panel"><div class="code-head"><b>sketch.ino</b><button id="download">Download .ino</button></div><pre id="arduino-code"></pre></section><section id="console-panel" class="panel console-panel"><div id="console"><p>Connect an Arduino with a USB data cable to open the serial monitor.</p></div><div class="send"><input id="serial-input" placeholder="Send a line…" disabled><button id="serial-send" disabled>Send</button></div></section></div></section><aside class="stage-pane"><div class="stage-menu"><div class="run-controls"><button class="run" title="Generate and run">▶</button><button class="stop" title="Disconnect">■</button></div><div class="stage-size"><button title="Small stage">◩</button><button class="selected" title="Large stage">▣</button><button title="Full screen">⛶</button></div></div><div class="device-stage"><div class="stage-status"><span id="status">Arduino offline</span><i></i></div><div class="arduino-board"><div class="usb-port"></div><div class="pin-row top"></div><div class="board-chip"></div><strong>ARDUINO</strong><b>UNO</b><div class="pin-row bottom"></div><div class="board-led"></div></div><p>Connect with a USB data cable</p></div><div class="device-selector"><div class="device-info"><span class="device-thumb">∞</span><label>Board<select id="board" aria-label="Board"><option value="uno">Arduino Uno</option><option value="nano">Arduino Nano</option><option value="nanoOldBootloader">Nano (old bootloader/clone)</option><option value="proMini">Pro Mini</option><option value="lgt8f328p">LGT8F328P / modified Uno</option><option value="mega">Mega 2560</option><option value="custom">Custom / modified board…</option></select></label></div><button class="add-device" title="Choose an Arduino board">＋</button></div></aside></main>
<div id="modal" class="modal" hidden><div class="dialog"><button class="close" aria-label="Close">×</button><h2>Upload over USB</h2><p>Compile the generated sketch anywhere once, then choose its <b>.hex</b> file. The browser flashes supported AVR boards directly through your USB uploading cable—no IDE installation needed.</p><label>1. Firmware file<input id="hex-file" type="file" accept=".hex,text/plain"></label><label>2. Upload profile<select id="upload-board"><option value="uno">Uno / Optiboot</option><option value="nano">Nano (new bootloader)</option><option value="nanoOldBootloader">Nano / clone (old bootloader)</option><option value="proMini">Pro Mini</option><option value="lgt8f328p">LGT8F328P</option></select></label><label class="verify"><input id="verify" type="checkbox" checked> Verify after uploading</label><button id="flash" class="flash">Choose a .hex file</button><progress id="progress" max="100" value="0"></progress><small id="upload-note">Web Serial requires desktop Chrome or Edge and HTTPS.</small></div></div>
<div id="toast" class="toast" role="status"></div>`;

Blockly.ScratchMsgs?.setLocale?.('en');
const workspace=Blockly.inject('blockly',{toolbox,media:'./media/',scrollbars:true,trashcan:false,comments:true,zoom:{controls:true,wheel:true,startScale:.8,maxScale:1.4,minScale:.35,scaleSpeed:1.1}});
const generator=createArduinoGenerator();
const $=selector=>document.querySelector(selector);let port,reader;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function generate(){const code=generator.workspaceToCode(workspace);$('#arduino-code').textContent=code;return code}
function loadStarter(){const xml=Blockly.Xml.textToDom(`<xml><variables><variable type="">counter</variable></variables><block type="arduino_start" x="70" y="50"><statement name="SUBSTACK"><block type="arduino_pin_mode"><field name="PIN">13</field><field name="MODE">OUTPUT</field><next><block type="arduino_digital_write"><field name="PIN">13</field><field name="STATE">HIGH</field><next><block type="arduino_wait"><field name="MS">500</field><next><block type="arduino_digital_write"><field name="PIN">13</field><field name="STATE">LOW</field><next><block type="arduino_wait"><field name="MS">500</field></block></next></block></next></block></next></block></next></block></statement></block></xml>`);Blockly.Xml.domToWorkspace(xml,workspace)}
const saved=localStorage.getItem('turboarduino-workspace');if(saved){try{Blockly.Xml.domToWorkspace(Blockly.Xml.textToDom(saved),workspace)}catch{loadStarter()}}else loadStarter();
workspace.addChangeListener(()=>{clearTimeout(window.saveTimer);window.saveTimer=setTimeout(()=>localStorage.setItem('turboarduino-workspace',Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace))),250)});
$('.editor-tabs').addEventListener('click',event=>{const button=event.target.closest('.tab');if(!button)return;if(button.dataset.panel==='arduino')generate();document.querySelectorAll('.tab,.panel').forEach(el=>el.classList.remove('active'));button.classList.add('active');$(`#${button.dataset.panel}-panel`).classList.add('active');if(button.dataset.panel==='blocks')setTimeout(()=>Blockly.svgResize(workspace))});
$('.run').onclick=()=>{generate();toast('Arduino code generated')};$('.stop').onclick=async()=>{await reader?.cancel();await port?.close();port=null;$('#status').textContent='Arduino offline'};
$('#project-name').value=localStorage.getItem('turboarduino-name')||'Blink';$('#project-name').oninput=e=>localStorage.setItem('turboarduino-name',e.target.value);
$('#file').onclick=()=>{if(confirm('Start a new Arduino project?')){localStorage.removeItem('turboarduino-workspace');location.reload()}};
$('#examples').onclick=()=>toast('Blink is loaded. More examples can be built from the full block palette.');$('#help').onclick=()=>toast('Build with TurboWarp blocks, generate C++, then upload a compiled HEX over USB.');$('#add-extension').onclick=()=>toast('Arduino hardware blocks are installed as the purple Hardware extension.');
$('#download').onclick=()=>{const url=URL.createObjectURL(new Blob([generate()],{type:'text/x-arduino'}));const link=Object.assign(document.createElement('a'),{href:url,download:($('#project-name').value.replace(/[^a-z0-9_-]/gi,'_')||'sketch')+'.ino'});link.click();setTimeout(()=>URL.revokeObjectURL(url),0)};
async function connect(){if(!navigator.serial)return toast('Web Serial needs desktop Chrome or Edge.');try{port=await navigator.serial.requestPort();await port.open({baudRate:9600});$('#status').textContent='Arduino connected · 9600 baud';$('#serial-input').disabled=$('#serial-send').disabled=false;$('#console').innerHTML='<p class="good">● USB serial connected</p>';const decoder=new TextDecoderStream();port.readable.pipeTo(decoder.writable);reader=decoder.readable.getReader();while(port?.readable){const {value,done}=await reader.read();if(done)break;if(value){const line=document.createElement('pre');line.textContent=value;$('#console').append(line);$('#console').scrollTop=$('#console').scrollHeight}}}catch(error){if(error.name!=='NotFoundError')toast(`Connection failed: ${error.message}`)}}
$('#connect').onclick=connect;$('#serial-send').onclick=async()=>{if(!port?.writable)return;const writer=port.writable.getWriter();await writer.write(new TextEncoder().encode($('#serial-input').value+'\n'));writer.releaseLock();$('#serial-input').value=''};
const modal=$('#modal');$('#upload').onclick=()=>{generate();$('#upload-board').value=['uno','nano','nanoOldBootloader','proMini','lgt8f328p'].includes($('#board').value)?$('#board').value:'uno';modal.hidden=false};$('.close').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};$('#hex-file').onchange=()=>{$('#flash').textContent=$('#hex-file').files[0]?'Flash firmware':'Choose a .hex file'};
$('#flash').onclick=async()=>{const file=$('#hex-file').files[0];if(!file)return toast('Choose a compiled .hex firmware file first.');if(!navigator.serial)return toast('Uploading requires Web Serial in Chrome or Edge.');try{$('#flash').disabled=true;$('#upload-note').textContent='Opening USB uploader…';const {upload,boards}=await import('web-arduino-uploader/dist/index.js');const url=URL.createObjectURL(file);await upload(boards[$('#upload-board').value],url,value=>{$('#progress').value=value;$('#upload-note').textContent=`Uploading… ${value}%`},$('#verify').checked);URL.revokeObjectURL(url);$('#upload-note').textContent='Upload complete — your Arduino is running!';toast('Firmware uploaded successfully')}catch(error){$('#upload-note').textContent=`Upload failed: ${error.message}`;toast('Upload failed — check the board profile and cable.')}finally{$('#flash').disabled=false}};
$('#board').onchange=()=>{const custom=$('#board').value==='custom';if(custom){const name=prompt('Name this modified Arduino / compatible board:','Custom ATmega328P');if(name){$('#board').selectedOptions[0].textContent=name;localStorage.setItem('turboarduino-custom-board',name)}toast('Use Hardware blocks freely; pin numbers are not limited. Choose its bootloader profile when uploading.')}};
const customName=localStorage.getItem('turboarduino-custom-board');if(customName)$('#board').querySelector('[value=custom]').textContent=customName;
